version: '3'
services:
  dwish-db:
    image: postgres:15.2-alpine
    container_name: dwish-postgres-15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST} 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - dwish-api-network
  
  dwish-redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  dwish-web:
    build: .
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - dwish-db
    ports:
      - "3000:3000"
    networks:
      - dwish-api-network
    tty: true
    stdin_open: true
  
  dwish-pgadmin:
    image: dpage/pgadmin4
    container_name: dwish-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@pg.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "15432:80"
    depends_on:
      - dwish-db
    networks:
      - dwish-api-network

volumes:
  postgres_data: {}
  app-storage: {}

networks:
  dwish-api-network:
    driver: bridge